baseURL = "http://example.org/"
languageCode = "fr-fr"
theme = "fapThème"
title = "Fabrique à projets "
[[menu.footer]]
name = "Privacy"
url = "/privacy"
weight = 1
[[menu.footer]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Contact"
url = "/Contact"
weight = 1
[[menu.main]]
name = "Les étudiants"
url = "/Etudiants"
weight = 2
[[menu.main]]
name = "Les projets"
url = "/projets"
weight = 3
[[menu.main]]
name = "L'école"
url = "/lecole.html"
weight = 4
[[menu.social]]
name = "Twitter"
pre = "<i class='fab fa-twitter'></i>"
url = "https://twitter.com/pakstech"
weight = 1
[[menu.social]]
name = "YouTube"
pre = "<i class='fab fa-youtube'></i>"
url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
weight = 2
[[menu.social]]
name = "GitHub"
pre = "<i class='fab fa-github'></i>"
url = "https://github.com/pakstech"
weight = 3
[params]
description = "My site description"
