baseURL = "http://example.org/"
languageCode = "fr-fr"
theme = "fapThème"
[params]
    description = "My site description"

[[menu.main]]
  name = "L'école"
  url = "/pages/Lecole"

[[menu.main]]
  name = "Les projets"
  url = "/pages/projets"

[[menu.main]]
  name = "Les étudiants"
  url = "/pages/Etudiants"

[[menu.main]]
  name = "Contact"
  url = "/pages/Contact"





[[menu.social]]
name = "GitHub"
pre = "<i class='fab fa-github'></i>"
url = "https://github.com/pakstech"
weight = 3
[[menu.social]]
name = "YouTube"
pre = "<i class='fab fa-youtube'></i>"
url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
weight = 2
[[menu.social]]
name = "Twitter"
pre = "<i class='fab fa-twitter'></i>"
url = "https://twitter.com/pakstech"
weight = 1
[params]
description = "My site description"
