baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Fabrique à projets "
theme = "fapThème"
[params]
    description = "My site description"

[[menu.main]]
  name = "L'école"
  url = "/pages/Lecole"

[[menu.main]]
  name = "Les projets"
  url = "/pages/projets"

[[menu.main]]
  name = "Les étudiants"
  url = "/pages/Etudiants"

[[menu.main]]
  name = "Contact"
  url = "/pages/Contact"





[[menu.social]]
    name = "GitHub"
    url = "https://github.com/pakstech"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"
  
